# xp-framework/ast

language: php

dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-master.sh > xp-run
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth

script:
  - sh xp-run xp.unittest.TestRunner src/test/php
