# xp-framework/compiler

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - master

matrix:
  allow_failures:
    - php: master

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-8.1.7.sh > xp-run
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth

script:
  - sh xp-run xp.unittest.TestRunner src/test/php
